// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hook.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Uploaded data
type Upload struct {
	// Unique integer identifier of the uploaded file
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Total file size in bytes specified in the NewUpload call
	Size int64 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	// Indicates whether the total file size is deferred until later
	SizeIsDeferred bool `protobuf:"varint,3,opt,name=SizeIsDeferred,proto3" json:"SizeIsDeferred,omitempty"`
	// Offset in bytes (zero-based)
	Offset   int64             `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	MetaData map[string]string `protobuf:"bytes,5,rep,name=metaData,proto3" json:"metaData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Indicates that this is a partial upload which will later be used to form
	// a final upload by concatenation. Partial uploads should not be processed
	// when they are finished since they are only incomplete chunks of files.
	IsPartial bool `protobuf:"varint,6,opt,name=isPartial,proto3" json:"isPartial,omitempty"`
	// Indicates that this is a final upload
	IsFinal bool `protobuf:"varint,7,opt,name=isFinal,proto3" json:"isFinal,omitempty"`
	// If the upload is a final one (see IsFinal) this will be a non-empty
	// ordered slice containing the ids of the uploads of which the final upload
	// will consist after concatenation.
	PartialUploads []string `protobuf:"bytes,8,rep,name=partialUploads,proto3" json:"partialUploads,omitempty"`
	// Storage contains information about where the data storage saves the upload,
	// for example a file path. The available values vary depending on what data
	// store is used. This map may also be nil.
	Storage              map[string]string `protobuf:"bytes,9,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Upload) Reset()         { *m = Upload{} }
func (m *Upload) String() string { return proto.CompactTextString(m) }
func (*Upload) ProtoMessage()    {}
func (*Upload) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{0}
}

func (m *Upload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upload.Unmarshal(m, b)
}
func (m *Upload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upload.Marshal(b, m, deterministic)
}
func (m *Upload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upload.Merge(m, src)
}
func (m *Upload) XXX_Size() int {
	return xxx_messageInfo_Upload.Size(m)
}
func (m *Upload) XXX_DiscardUnknown() {
	xxx_messageInfo_Upload.DiscardUnknown(m)
}

var xxx_messageInfo_Upload proto.InternalMessageInfo

func (m *Upload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Upload) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Upload) GetSizeIsDeferred() bool {
	if m != nil {
		return m.SizeIsDeferred
	}
	return false
}

func (m *Upload) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Upload) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Upload) GetIsPartial() bool {
	if m != nil {
		return m.IsPartial
	}
	return false
}

func (m *Upload) GetIsFinal() bool {
	if m != nil {
		return m.IsFinal
	}
	return false
}

func (m *Upload) GetPartialUploads() []string {
	if m != nil {
		return m.PartialUploads
	}
	return nil
}

func (m *Upload) GetStorage() map[string]string {
	if m != nil {
		return m.Storage
	}
	return nil
}

type HTTPRequest struct {
	// Method is the HTTP method, e.g. POST or PATCH
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// URI is the full HTTP request URI, e.g. /files/fooo
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// RemoteAddr contains the network address that sent the request
	RemoteAddr           string   `protobuf:"bytes,3,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPRequest) Reset()         { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()    {}
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{1}
}

func (m *HTTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPRequest.Unmarshal(m, b)
}
func (m *HTTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPRequest.Marshal(b, m, deterministic)
}
func (m *HTTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPRequest.Merge(m, src)
}
func (m *HTTPRequest) XXX_Size() int {
	return xxx_messageInfo_HTTPRequest.Size(m)
}
func (m *HTTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPRequest proto.InternalMessageInfo

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HTTPRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

// Hook's data
type Hook struct {
	// Upload contains information about the upload that caused this hook
	// to be fired.
	Upload *Upload `protobuf:"bytes,1,opt,name=upload,proto3" json:"upload,omitempty"`
	// HTTPRequest contains details about the HTTP request that reached
	// tusd.
	HttpRequest          *HTTPRequest `protobuf:"bytes,2,opt,name=httpRequest,proto3" json:"httpRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Hook) Reset()         { *m = Hook{} }
func (m *Hook) String() string { return proto.CompactTextString(m) }
func (*Hook) ProtoMessage()    {}
func (*Hook) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{2}
}

func (m *Hook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hook.Unmarshal(m, b)
}
func (m *Hook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hook.Marshal(b, m, deterministic)
}
func (m *Hook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hook.Merge(m, src)
}
func (m *Hook) XXX_Size() int {
	return xxx_messageInfo_Hook.Size(m)
}
func (m *Hook) XXX_DiscardUnknown() {
	xxx_messageInfo_Hook.DiscardUnknown(m)
}

var xxx_messageInfo_Hook proto.InternalMessageInfo

func (m *Hook) GetUpload() *Upload {
	if m != nil {
		return m.Upload
	}
	return nil
}

func (m *Hook) GetHttpRequest() *HTTPRequest {
	if m != nil {
		return m.HttpRequest
	}
	return nil
}

// Request data to send hook
type SendRequest struct {
	// The hook data
	Hook                 *Hook    `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{3}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetHook() *Hook {
	if m != nil {
		return m.Hook
	}
	return nil
}

// Response that contains data for sended hook
type SendResponse struct {
	// The response of the hook.
	Response             *any.Any `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{4}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetResponse() *any.Any {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Upload)(nil), "v1.Upload")
	proto.RegisterMapType((map[string]string)(nil), "v1.Upload.MetaDataEntry")
	proto.RegisterMapType((map[string]string)(nil), "v1.Upload.StorageEntry")
	proto.RegisterType((*HTTPRequest)(nil), "v1.HTTPRequest")
	proto.RegisterType((*Hook)(nil), "v1.Hook")
	proto.RegisterType((*SendRequest)(nil), "v1.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "v1.SendResponse")
}

func init() { proto.RegisterFile("hook.proto", fileDescriptor_3eef30da1c11ee1b) }

var fileDescriptor_3eef30da1c11ee1b = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x1f, 0x75, 0xec, 0x71, 0x29, 0xd5, 0xaa, 0x82, 0x25, 0xaa, 0x90, 0xe5, 0x03, 0xb2,
	0x54, 0xc9, 0x25, 0x81, 0x03, 0x0a, 0x17, 0x2a, 0x15, 0x54, 0x0e, 0x88, 0x6a, 0x53, 0xc4, 0x89,
	0xc3, 0x16, 0x6f, 0x12, 0x2b, 0x8e, 0xd7, 0xac, 0xd7, 0x91, 0xc2, 0x8f, 0xe2, 0x37, 0xa2, 0xfd,
	0x70, 0x63, 0x72, 0xeb, 0xc9, 0x33, 0x6f, 0xde, 0xbc, 0x79, 0x9e, 0x1d, 0x80, 0x15, 0xe7, 0xeb,
	0xbc, 0x11, 0x5c, 0x72, 0xe4, 0x6e, 0x27, 0xe3, 0x97, 0x4b, 0xce, 0x97, 0x15, 0xbb, 0xd4, 0xc8,
	0x7d, 0xb7, 0xb8, 0xa4, 0xf5, 0xce, 0x94, 0xd3, 0xbf, 0x1e, 0x04, 0xdf, 0x9b, 0x8a, 0xd3, 0x02,
	0x9d, 0x80, 0x5b, 0x16, 0xd8, 0x49, 0x9c, 0x2c, 0x22, 0x6e, 0x59, 0x20, 0x04, 0xfe, 0xbc, 0xfc,
	0xc3, 0xb0, 0x9b, 0x38, 0x99, 0x47, 0x74, 0x8c, 0x5e, 0xc3, 0x89, 0xfa, 0x7e, 0x69, 0xaf, 0xd9,
	0x82, 0x09, 0xc1, 0x0a, 0xec, 0x25, 0x4e, 0x16, 0x92, 0x03, 0x14, 0x3d, 0x87, 0xe0, 0xdb, 0x62,
	0xd1, 0x32, 0x89, 0x7d, 0xdd, 0x6d, 0x33, 0xf4, 0x0e, 0xc2, 0x0d, 0x93, 0xf4, 0x9a, 0x4a, 0x8a,
	0x8f, 0x12, 0x2f, 0x8b, 0xa7, 0x38, 0xdf, 0x4e, 0x72, 0xe3, 0x20, 0xff, 0x6a, 0x4b, 0x9f, 0x6a,
	0x29, 0x76, 0xe4, 0x81, 0x89, 0xce, 0x21, 0x2a, 0xdb, 0x5b, 0x2a, 0x64, 0x49, 0x2b, 0x1c, 0xe8,
	0x81, 0x7b, 0x00, 0x61, 0x18, 0x95, 0xed, 0xe7, 0xb2, 0xa6, 0x15, 0x1e, 0xe9, 0x5a, 0x9f, 0x2a,
	0xb7, 0x8d, 0x21, 0x99, 0x01, 0x2d, 0x0e, 0x13, 0x2f, 0x8b, 0xc8, 0x01, 0x8a, 0x26, 0x30, 0x6a,
	0x25, 0x17, 0x74, 0xc9, 0x70, 0xa4, 0x4d, 0xbd, 0x18, 0x98, 0x9a, 0x9b, 0x8a, 0xf1, 0xd4, 0xf3,
	0xc6, 0x1f, 0xe0, 0xe9, 0x7f, 0x6e, 0xd1, 0x29, 0x78, 0x6b, 0xb6, 0xb3, 0xeb, 0x53, 0x21, 0x3a,
	0x83, 0xa3, 0x2d, 0xad, 0x3a, 0xb3, 0xc0, 0x88, 0x98, 0x64, 0xe6, 0xbe, 0x77, 0xc6, 0x33, 0x38,
	0x1e, 0xaa, 0x3e, 0xa6, 0x37, 0xfd, 0x01, 0xf1, 0xcd, 0xdd, 0xdd, 0x2d, 0x61, 0xbf, 0x3b, 0xd6,
	0x4a, 0xb5, 0xe8, 0x0d, 0x93, 0x2b, 0xde, 0x3f, 0x9c, 0xcd, 0x94, 0x64, 0x27, 0x4a, 0xdb, 0xae,
	0x42, 0xf4, 0x0a, 0x40, 0xb0, 0x0d, 0x97, 0xec, 0xaa, 0x28, 0x84, 0x7e, 0xb6, 0x88, 0x0c, 0x90,
	0xf4, 0x27, 0xf8, 0x37, 0x9c, 0xaf, 0x51, 0x0a, 0x41, 0xa7, 0xff, 0x5c, 0x2b, 0xc6, 0x53, 0xd8,
	0xef, 0x82, 0xd8, 0x0a, 0x9a, 0x40, 0xbc, 0x92, 0xb2, 0xb1, 0x26, 0xf4, 0x94, 0x78, 0xfa, 0x4c,
	0x11, 0x07, 0xde, 0xc8, 0x90, 0x93, 0x5e, 0x40, 0x3c, 0x67, 0x75, 0xd1, 0xfb, 0x3e, 0x07, 0x5f,
	0x1d, 0xa9, 0x9d, 0x11, 0xea, 0x56, 0xce, 0xd7, 0x44, 0xa3, 0xe9, 0x47, 0x38, 0x36, 0xe4, 0xb6,
	0xe1, 0x75, 0xcb, 0xd0, 0x1b, 0x08, 0x85, 0x8d, 0x6d, 0xc7, 0x59, 0x6e, 0x6e, 0x3a, 0xef, 0x6f,
	0x3a, 0xbf, 0xaa, 0x77, 0xe4, 0x81, 0x35, 0x9d, 0x41, 0xac, 0xf4, 0xe6, 0x4c, 0x6c, 0xcb, 0x5f,
	0x0c, 0x5d, 0x80, 0xaf, 0x04, 0x91, 0xf6, 0x38, 0xf0, 0x31, 0x3e, 0xdd, 0x03, 0xa6, 0x33, 0x7d,
	0x72, 0x1f, 0x68, 0xcd, 0xb7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x87, 0x7b, 0x45, 0xd1, 0x47,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HookServiceClient is the client API for HookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HookServiceClient interface {
	// Sends a hook
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type hookServiceClient struct {
	cc *grpc.ClientConn
}

func NewHookServiceClient(cc *grpc.ClientConn) HookServiceClient {
	return &hookServiceClient{cc}
}

func (c *hookServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/v1.HookService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HookServiceServer is the server API for HookService service.
type HookServiceServer interface {
	// Sends a hook
	Send(context.Context, *SendRequest) (*SendResponse, error)
}

func RegisterHookServiceServer(s *grpc.Server, srv HookServiceServer) {
	s.RegisterService(&_HookService_serviceDesc, srv)
}

func _HookService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HookService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.HookService",
	HandlerType: (*HookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _HookService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hook.proto",
}
